# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2e607b587375a7aa59653d5c535bff3a35f0a10bc44402e1d88f9dc63cd254173f171cf78ee5d773d5156ceebdb956ba8becc14115c8f888ee605b7667b93c9

test:
  secret_key_base: 84aa1e9c82eb982576a3429de68622decab491490daf15f0440a0ba390348dfc22a413107b50bf01e14e867686f6dd9f40f71789f2f6c04daf6aa1694d73abc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
